apiVersion: v1
kind: Namespace
metadata:
  name: cilium
---
apiVersion: source.toolkit.fluxcd.io/v1beta1
kind: HelmRepository
metadata:
  name: cilium
  namespace: cilium
spec:
  url: https://helm.cilium.io/
  interval: 10m
---
apiVersion: helm.toolkit.fluxcd.io/v2beta1
kind: HelmRelease
metadata:
  name: cilium
  namespace: cilium
spec:
  interval: 5m
  chart:
    spec:
      chart: cilium
      version: "1.10.3"
      sourceRef:
        kind: HelmRepository
        name: cilium
        namespace: cilium
      interval: 1m
  values:
    nodeinit:
      enabled: true
    kubeProxyReplacement: strict 
    hostServices:
      enabled: true
    externalIPs:
      enabled: true
    nodePort:
      enabled: true
    egressGateway:
      enabled: true
    k8sServiceHost: k8s-guide-control-plane
    k8sServicePort: "6443"
    hostPort:
      enabled: true
    bpf:
      masquerade: true


